//! CLI command implementations.

pub mod balance;
pub mod build_l2;
pub mod delete;
pub mod deposit;
pub mod earnings;
pub mod init;
pub mod list;
pub mod mcp_server;
pub mod merge_l2;
pub mod preview;
pub mod publish;
pub mod query;
pub mod reference;
pub mod settle;
pub mod start;
pub mod status;
pub mod stop;
pub mod synthesize;
pub mod update;
pub mod versions;
pub mod visibility;
pub mod whoami;
pub mod withdraw;

// Re-export command handlers
pub use balance::balance;
pub use build_l2::build_l2;
pub use delete::delete;
pub use deposit::deposit;
pub use earnings::earnings;
pub use init::init;
pub use list::list;
pub use mcp_server::mcp_server;
pub use merge_l2::merge_l2;
pub use preview::preview;
pub use publish::publish;
pub use query::query;
pub use reference::reference;
pub use settle::settle;
pub use start::{start, start_daemon_sync};
pub use status::status;
pub use stop::stop;
pub use synthesize::synthesize;
pub use update::update;
pub use versions::versions;
pub use visibility::visibility;
pub use whoami::whoami;
pub use withdraw::withdraw;
