#!/bin/bash
# Initialize a 3-node Nodalync cluster
# Generates identities and configuration files for each node

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$DOCKER_DIR/config"
DATA_DIR="$DOCKER_DIR/data"

# Default settings
IMAGE="${NODALYNC_IMAGE:-gabrielgiangi/nodalync:latest}"
PASSWORD="${NODALYNC_PASSWORD:-testpassword}"
SETTLEMENT_NETWORK="${SETTLEMENT_NETWORK:-mock}"
CONTRACT_ID="${HEDERA_CONTRACT_ID:-0.0.7729011}"

# The default data directory inside the container (set by NODALYNC_DATA_DIR in Dockerfile)
CONTAINER_DATA_DIR="/home/nodalync/.nodalync"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Create directories
log_info "Creating directories..."
mkdir -p "$CONFIG_DIR"
mkdir -p "$DATA_DIR/node1"
mkdir -p "$DATA_DIR/node2"
mkdir -p "$DATA_DIR/node3"

# Clean any existing config
rm -f "$CONFIG_DIR"/*.toml
rm -f "$CONFIG_DIR"/peer-ids.env

# Phase 1: Initialize identities for each node
log_info "Phase 1: Generating node identities..."

# Use simple variables instead of associative arrays (for bash 3.x compatibility)
PEER_ID_1=""
PEER_ID_2=""
PEER_ID_3=""
LIBP2P_PEER_ID_1=""
LIBP2P_PEER_ID_2=""
LIBP2P_PEER_ID_3=""

for i in 1 2 3; do
    NODE_DATA="$DATA_DIR/node$i"

    log_info "Initializing node$i..."

    # Clear existing identity if present
    rm -rf "$NODE_DATA/identity" 2>/dev/null || true

    # Run nodalync init in a temporary container
    # Mount to the container's default data directory
    docker run --rm \
        -v "$NODE_DATA:$CONTAINER_DATA_DIR" \
        -e NODALYNC_PASSWORD="$PASSWORD" \
        "$IMAGE" \
        init 2>&1 | grep -v "^$" || true

    # Extract peer IDs using whoami
    WHOAMI_OUTPUT=$(docker run --rm \
        -v "$NODE_DATA:$CONTAINER_DATA_DIR" \
        -e NODALYNC_PASSWORD="$PASSWORD" \
        "$IMAGE" \
        whoami --format json 2>&1)

    # Parse nodalync peer_id (for display)
    PEER_ID=$(echo "$WHOAMI_OUTPUT" | grep -o '"peer_id"[[:space:]]*:[[:space:]]*"[^"]*"' | grep -o 'ndl[^"]*')

    # Parse libp2p_peer_id (for bootstrap addresses) - format: 12D3KooW...
    LIBP2P_PEER_ID=$(echo "$WHOAMI_OUTPUT" | grep -o '"libp2p_peer_id"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"libp2p_peer_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')

    if [ -z "$PEER_ID" ] || [ -z "$LIBP2P_PEER_ID" ]; then
        log_error "Failed to get peer ID for node$i"
        log_error "whoami output: $WHOAMI_OUTPUT"
        exit 1
    fi

    # Store in individual variables
    case $i in
        1) PEER_ID_1="$PEER_ID"; LIBP2P_PEER_ID_1="$LIBP2P_PEER_ID" ;;
        2) PEER_ID_2="$PEER_ID"; LIBP2P_PEER_ID_2="$LIBP2P_PEER_ID" ;;
        3) PEER_ID_3="$PEER_ID"; LIBP2P_PEER_ID_3="$LIBP2P_PEER_ID" ;;
    esac

    log_info "node$i peer ID: $PEER_ID (libp2p: $LIBP2P_PEER_ID)"
done

# Phase 2: Generate configuration files
log_info "Phase 2: Generating configuration files..."

# Create bootstrap addresses for all nodes (full mesh)
NODE1_BOOTSTRAP_ADDR="/ip4/172.28.0.10/tcp/9000/p2p/${LIBP2P_PEER_ID_1}"
NODE2_BOOTSTRAP_ADDR="/ip4/172.28.0.11/tcp/9000/p2p/${LIBP2P_PEER_ID_2}"
NODE3_BOOTSTRAP_ADDR="/ip4/172.28.0.12/tcp/9000/p2p/${LIBP2P_PEER_ID_3}"

for i in 1 2 3; do
    CONFIG_FILE="$CONFIG_DIR/node$i-config.toml"

    # Each node bootstraps from the OTHER two nodes (full mesh connectivity)
    # This ensures ephemeral CLI contexts can always find peers
    case $i in
        1) BOOTSTRAP_NODES="[\"$NODE2_BOOTSTRAP_ADDR\", \"$NODE3_BOOTSTRAP_ADDR\"]" ;;
        2) BOOTSTRAP_NODES="[\"$NODE1_BOOTSTRAP_ADDR\", \"$NODE3_BOOTSTRAP_ADDR\"]" ;;
        3) BOOTSTRAP_NODES="[\"$NODE1_BOOTSTRAP_ADDR\", \"$NODE2_BOOTSTRAP_ADDR\"]" ;;
    esac

    cat > "$CONFIG_FILE" << EOF
# Nodalync Node $i Configuration
# Generated by init-cluster.sh

[identity]
keyfile = "$CONTAINER_DATA_DIR/identity/keypair.key"

[storage]
content_dir = "$CONTAINER_DATA_DIR/content"
database = "$CONTAINER_DATA_DIR/nodalync.db"
cache_dir = "$CONTAINER_DATA_DIR/cache"
cache_max_size_mb = 1000

[network]
enabled = true
listen_addresses = ["/ip4/0.0.0.0/tcp/9000"]
bootstrap_nodes = $BOOTSTRAP_NODES

[settlement]
network = "$SETTLEMENT_NETWORK"
contract_id = "$CONTRACT_ID"

[economics]
default_price = 0.10
auto_settle_threshold = 100.0

[display]
default_format = "human"
show_previews = true
max_search_results = 20
EOF

    log_info "Created $CONFIG_FILE"
done

# Save peer IDs to environment file
cat > "$CONFIG_DIR/peer-ids.env" << EOF
# Peer IDs for the 3-node cluster
# Generated by init-cluster.sh

# Nodalync peer IDs (for display)
NODE1_PEER_ID=${PEER_ID_1}
NODE2_PEER_ID=${PEER_ID_2}
NODE3_PEER_ID=${PEER_ID_3}

# Libp2p peer IDs (for bootstrap/DHT)
NODE1_LIBP2P_PEER_ID=${LIBP2P_PEER_ID_1}
NODE2_LIBP2P_PEER_ID=${LIBP2P_PEER_ID_2}
NODE3_LIBP2P_PEER_ID=${LIBP2P_PEER_ID_3}

# Bootstrap address (for external connections)
NODE1_BOOTSTRAP_ADDR=$NODE1_BOOTSTRAP_ADDR
EOF

log_info "Saved peer IDs to $CONFIG_DIR/peer-ids.env"

# Summary
echo ""
echo "=========================================="
echo "Cluster initialization complete!"
echo "=========================================="
echo ""
echo "Node 1 (bootstrap): ${PEER_ID_1}"
echo "Node 2:             ${PEER_ID_2}"
echo "Node 3:             ${PEER_ID_3}"
echo ""
echo "Bootstrap address: $NODE1_BOOTSTRAP_ADDR"
echo ""
echo "To start the cluster:"
echo "  cd $DOCKER_DIR && docker compose up -d"
echo ""
echo "To check status:"
echo "  docker compose ps"
echo ""
